file_name = input("Enter file name: ")
file_name = file_name + '.txt'
text = input("Enter text for writing to the file: ")
f = open(file_name, "w")
f.write(text+'\n')
f.close()
add_text = input("What do you want to append to txt file? ")
f = open(file_name, "a")
f.write(add_text+"\n")
f.close()
f = open(file_name)
arr = f.readlines()
print(arr)
f.close()
